### ISSUE TITLE
How to set Z-Offset without an LCD screen?

### ISSUE THREAD

**Issue by guyman70718** [Printrbot/printrboardmodernmarlin#22]
I have just flashed my Printrbot Play with "RevFv1.0_Printrbot_Play.hex" (the 1.1 only had Heated Bed version) and I want to set the Z Offset to be like 0.1mm higher than it is now. I read the Readme instructions on how to do this, but it says to use the measurement on the LCD Screen to get the offset. I don't have an LCD screen, so is the measurement from M114 good enough?

On another note, is there a way to add an LCD to my printer that does not have one using this custom firmware?

**Comment by drphil3d** [comment]
There isn't support for LCD because the latest version of marlin requires 98% of the very limited 128k of memory the Printrboard has.


Adjusting your Z-offset is very easy with babystepping, you have to be printing while adjusting the offset.
If you want to raise the hotend up .1mm higher just type
M290 Z0.1
save it with M500

If you send the command multiple times it increases the total distance
M290 Z0.1
M290 Z0.1

total distance would be 0.2 mm

do this adjustment while the first layer is printing.
